services:
  nginx:
    container_name: mt-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - mt-frontend-dist:/usr/share/nginx/html

  frontend:
    container_name: mt-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file: ./frontend/.env
    environment:
      VITE_SERVER_ORIGIN: http://localhost
    working_dir: /app
    volumes:
      - mt-frontend-dist:/app/dist
    command: "npm run dev"

  backend:
    container_name: mt-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm run dev

volumes:
  mt-frontend-dist:
